# Jekyll configuration for jake test blog
title: jake test blog
description: A blog managed by CLI Blog
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Post permalink structure
permalink: /posts/:slug/

# Defaults for posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"


# Exclude files
exclude:
  - README.md
  - .gitkeep
